apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: triton
  annotations:
      prometheus.io/scrape: 'true'
      prometheus.io/port:   '8002'

spec:
  selector:
  template:
    metadata:
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8002"
    spec:
      containers:
        - name: triton-server
          nodeSelector:
            kubernetes.io/role: node
          image: anthonyfong/jetson-triton
          imagePullPolicy: Always
          args:
            [
              "--min-supported-compute-capability=5.3",
              "--model-repository=/opt/triton/models",
              "--backend-config=tensorflow,version=2",
            ]
          volumeMounts:
            - mountPath: /dev/shm
              name: dshm
          ports:
            - containerPort: 8000
              name: http
            - containerPort: 8001
              name: grpc
            - containerPort: 8002
              name: metrics
      volumes:
        - name: dshm
          emptyDir:
            medium: Memory
