apiVersion: v1
kind: Service
metadata:
  name: triton
  annotations:
      prometheus.io/scrape: 'true'
      prometheus.io/port:   '8002'
spec:
  type: NodePort
  selector:
  ports:
    - protocol: TCP
      name: http
      port: 8000
      nodePort: 30800
      targetPort: 8000
    - protocol: TCP
      name: grpc
      port: 8001
      nodePort: 30801
      targetPort: 8001
    - protocol: TCP
      name: metrics
      nodePort: 30802
      port: 8002
      targetPort: 8002          
