{
 "title": "New dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Average queue time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by(model, kubernetes_pod_name) (nv_inference_queue_duration_us{model=\"yolov5\"}) / sum by(model, kubernetes_pod_name) (nv_inference_queue_duration_us{model=\"yolov5\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Inference count",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum by(kubernetes_pod_name, model) (nv_inference_count{model=\"yolov5\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Number of inference",
   "type": "stat",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(model) (nv_inference_count)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "QPS",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "avg by(kubernetes_pod_name, model) (rate(nv_inference_count{model=\"yolov5\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average inference duration",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "sum by(model, kubernetes_pod_name) (nv_inference_compute_infer_duration_us{model=\"yolov5\"}) / sum by(model, kubernetes_pod_name) (nv_inference_count)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}